name: Build and deploy Node.js app to Azure Web App - zoho-mail

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71F7F803EDDA47A8DA9A36979ED6D586 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8FA9BE9F1D2A48E09918932543F67CE9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4D64181BC594B9E99AA6E6E2ECD284D7 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'zoho-mail'
          slot-name: 'Production'
          package: .
